#!/usr/bin/env bash

set -e

. .env

HISTORICAL_URL="https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/storage/kv/namespaces/$CF_NAMESPACE_ID/values/cached_unofficial_src_covid19india.org_statewise_history"

getJsonFromGoogleSheetsHistory() {
  file="$1"
  d="$2"
  ./hack-historical-statewise.py $file $d | jq -c .
}

getLatestJson() {
  curl -fsSL https://api.rootnet.in/covid19-in/unofficial/covid19india.org/statewise |\
    jq '{"day": .data.lastRefreshed[0:10], "total":.data.total, "statewise": .data.statewise}'
}

getHistoricalJsonTillNow() {
  curl -fsSL -H "Authorization: Bearer $CF_API_TOKEN" "$HISTORICAL_URL" | jq ".data.history[] | select(.day != \"$1\")"
}

updateHistoricalJson() {
  j=/tmp/json.$$
  today=$(TZ=UTC date '+%Y-%m-%dT%H:%M:00.000Z')
  len=$(echo "$1" | jq '. | length')
  [ $len -lt 40 ] && echo "avoiding screwing up of history" >&2 && exit 1
  echo "$1" | jq -c "{\"success\": true, \"data\": {\"source\": \"covid19india.org\", \"lastRefreshed\": \"$today\", \"history\":.}}" > $j
  curl -fsSL -XPUT -d @$j -H "Content-Type: application/json; charset=utf-8" -H "Authorization: Bearer $CF_API_TOKEN" "$HISTORICAL_URL"
  rm -f "$j"
}

getPriorData() {
  for f in 14 15 16 17 18 19 20 21 22 23; do
    getJsonFromGoogleSheetsHistory "raw-googlesheets-history-copypaste-covid19india/$f-03" "2020-03-$f"
  done
  cat raw-googlesheets-history-copypaste-covid19india/statewise-history-03-29.json | jq -c '.data.history[]'
}

#updateHistoricalJson "$(getPriorData | jq -sc .)"

# Update using today's data
LATEST_JSON=$(getLatestJson)
TODAY=$(echo "$LATEST_JSON" | jq -r .day)
updateHistoricalJson "$({ getHistoricalJsonTillNow "$TODAY"; echo "$LATEST_JSON"; } | jq -cs .)"
